a = int(input("Enter an integer. a= "))
b = int(input("Enter an integer. b= "))
c = int(input("Enter an integer. c= "))
d = int(input("Enter an integer. d= "))
e = int(input("Enter an integer. e= "))
f = int(input("Enter an integer. f= "))

print("a**b-c*d+e-f=", (a**b-c*d+e-f))
print("Answer: The order of precedence is '(a^b)-(c*d)+e-f'")
print("First, we should calculate Exponential expression")
print("Second, we should calculate Product expression")
print("Finally, we should add or subtract all expressions respectively from left to the right.")