binary_input = int(input("Please enter a number in base 2: "), base=2)
print(binary_input)
octal_input = int(input("Please enter a number in octal: "), base=8)
print(octal_input)
hex_input = int(input("Please enter a number in hexadecimal: "), base=16)
print(hex_input)
