a = int(input("Please write an integer: "))
b = int(input("Please write an other integer: "))

print("a=", a)
print("b=", b)
print("(a==b) is", a==b)
print("(a!=b) is", a!=b)
print("(a>b) is", a>b)
print("(a<b) is", a<b)
print("(a<=b) is", a<=b)
print("(a>=b) is", a>=b)